Models/ConfigurationModel.cs
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Widgets.Goftino.Models
{
    public record ConfigurationModel : BaseNopModel
    {
	// able to set configuration for each store
        public int ActiveStoreScopeConfiguration { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.Goftino.Enable")]
        public bool Enable { get; set; }
        public bool Enable_OverrideForStore { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.Goftino.TrackingScript")]
        public string TrackingScript { get; set; }
        public bool TrackingScript_OverrideForStore { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.Goftino.GoftinoCode")]
        public string GoftinoCode { get; set; }
        public bool GoftinoCode_OverrideForStore { get; set; }
    }
}

Components/GoftinoViewComponent.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Nop.Core;
using Nop.Services.Configuration;
using Nop.Services.Logging;
using Nop.Web.Framework.Components;
using System;
using System.Threading.Tasks;

namespace Nop.Plugin.Widgets.Goftino.Components
{
    public class GoftinoViewComponent : NopViewComponent
    {
        #region Fields

        private readonly ILogger _logger;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        #endregion

        #region Ctor

        public GoftinoViewComponent(
            ILogger logger,
            ISettingService settingService,
            IStoreContext storeContext
        )
        {
            _logger = logger;
            _settingService = settingService;
            _storeContext = storeContext;
        }

        #endregion

        #region Utilities

        #endregion

        #region Methods

        /// <returns>A task that represents the asynchronous operation</returns>
        public async Task<IViewComponentResult> InvokeAsync(string widgetZone, object additionalData)
        {
            try
            {
                var currentStore = await _storeContext.GetCurrentStoreAsync();
                var goftinoSettings = await _settingService.LoadSettingAsync<GoftinoSettings>(currentStore.Id);
                if(!goftinoSettings.Enable)
                    return new HtmlContentViewComponentResult(new HtmlString(string.Empty));
                goftinoSettings.TrackingScript = goftinoSettings.TrackingScript.Replace("{GoftinoCode}", goftinoSettings.GoftinoCode);
                return View("~/Plugins/Widgets.Goftino/Views/PublicInfo.cshtml", goftinoSettings.TrackingScript);
            }
            catch (Exception ex)
            {
                await _logger.InsertLogAsync(Core.Domain.Logging.LogLevel.Error, "Error creating scripts for Google eCommerce tracking", ex.ToString());
            }
            return new HtmlContentViewComponentResult(new HtmlString(string.Empty));
        }

        #endregion
    }
}

Controllers/WidgetsGoftinoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Widgets.Goftino.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Widgets.Goftino.Controllers
{
    [Area(AreaNames.Admin)]
    [AuthorizeAdmin]
    [AutoValidateAntiforgeryToken]
    public class WidgetsGoftinoController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        #endregion

        #region Ctor

        public WidgetsGoftinoController(
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
        }

        #endregion

        #region Methods
        
        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var goftinoSettings = await _settingService.LoadSettingAsync<GoftinoSettings>(storeScope);

            var model = new ConfigurationModel
            {
                TrackingScript = goftinoSettings.TrackingScript,
                Enable = goftinoSettings.Enable,
                GoftinoCode = goftinoSettings.GoftinoCode,
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.TrackingScript_OverrideForStore = await _settingService.SettingExistsAsync(goftinoSettings, x => x.TrackingScript, storeScope);
                model.Enable_OverrideForStore = await _settingService.SettingExistsAsync(goftinoSettings, x => x.Enable, storeScope);
                model.GoftinoCode_OverrideForStore = await _settingService.SettingExistsAsync(goftinoSettings, x => x.GoftinoCode, storeScope);
            }

            return View("~/Plugins/Widgets.Goftino/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var goftinoSettings = await _settingService.LoadSettingAsync<GoftinoSettings>(storeScope);

            goftinoSettings.TrackingScript = model.TrackingScript;
            goftinoSettings.GoftinoCode = model.GoftinoCode;
            goftinoSettings.Enable = model.Enable;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            await _settingService.SaveSettingOverridablePerStoreAsync(goftinoSettings, x => x.TrackingScript, model.TrackingScript_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(goftinoSettings, x => x.Enable, model.Enable_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(goftinoSettings, x => x.GoftinoCode, model.GoftinoCode_OverrideForStore, storeScope, false);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        #endregion
    }
}

Views/Configure.cshtml
@model Nop.Plugin.Widgets.Goftino.Models.ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync(typeof(StoreScopeConfigurationViewComponent))

<form asp-controller="WidgetsGoftino" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                @T("Plugins.Widgets.Godtino.Instructions")              
            </div>
           </div>
        <div class="card card-default">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TrackingScript_OverrideForStore" asp-input="TrackingScript" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TrackingScript" />
                    </div>
                    <div class="col-md-9">
                        <nop-textarea asp-for="TrackingScript" />
                        <span asp-validation-for="TrackingScript"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="GoftinoCode_OverrideForStore" asp-input="GoftinoCode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="GoftinoCode" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="GoftinoCode" />
                        <span asp-validation-for="GoftinoCode"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Enable_OverrideForStore" asp-input="Enable" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Enable" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Enable" />
                        <span asp-validation-for="Enable"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        &nbsp;
                    </div>
                    <div class="col-md-9">
                        <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/PublicInfo.cshtml
@model string
@Html.Raw(Model)